### ISSUE TITLE
Make font color visible at some places in dark theme 

### ISSUE THREAD

**Issue by surbhiaudichya** [hifi-finance/docs#6]
Change the font color at some places to make it more visible in dark theme.
<img width="1440" alt="Screenshot 2021-12-13 at 8 59 02 PM" src="https://user-images.githubusercontent.com/44962041/145843589-de531404-5509-4270-a760-2bd1bac179f0.png">

**Comment by PaulRBerg** [comment]
Good catch! Fixed in https://github.com/hifi-finance/docs/commit/a5caf220b6be42934c46c7de703175df46ed7bca.
