### ISSUE TITLE
Unreadable links in dark mode

### ISSUE THREAD

**Issue by maxdesalle** [hifi-finance/docs#7]
![CleanShot 2021-12-13 at 18 40 20](https://user-images.githubusercontent.com/70470326/145987154-f386bbb0-c2cf-4680-807d-9f97834ef6d6.png)

Can probably be fixed by changing the color scheme in [this file](https://github.com/hifi-finance/docs/blob/main/src/css/custom.css).

**Comment by PaulRBerg** [comment]
Fixed in https://github.com/hifi-finance/docs/commit/282b29df33adbc3a8a324bdc2aaca590ed9ac2fb.
